<?php
declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

use EasySlugger\Utf8Slugger;
use PHPUnit\Framework\TestCase;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 08:46:21.
 */
class GlossaryLoaderTest extends TestCase
{

    /**
     * @var GlossaryLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        // Utf8Slugger cannot be mocked because it is static
        $slugger = new Utf8Slugger();

        $this->object = new GlossaryLoader(__DIR__ . '/fixtures/glossary-with-options.yml', $slugger);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    public function testLoadWithOptions(): void
    {
        $this->object->load(true);

        static::assertTrue($this->object->isLoaded());

        $options = [
            'coverage' => 'first',
            'elements' => ['chapter', 'prologue']
        ];

        static::assertEquals($options, $this->object->getOptions());
    }

    public function testLoadWithoutOptions(): void
    {
        $this->object->load();

        static::assertTrue($this->object->isLoaded());

        static::assertEquals(null, $this->object->getOptions());
    }


}
