<?php

namespace Trefoil\Helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 09:17:37.
 */
class TextPreserverTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TextPreserver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TextPreserver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Trefoil\Helpers\TextPreserver::setText
     * @covers Trefoil\Helpers\TextPreserver::getText
     */
    public function testNoChange()
    {
        $this->object->setText('Lorem ipsum');
        $this->assertEquals('Lorem ipsum', $this->object->getText());
    }

    /**
     * @covers Trefoil\Helpers\TextPreserver::preserveHtmlTags
     * @covers Trefoil\Helpers\TextPreserver::restore
     */
    public function testPreserveHtmlTags()
    {
        $html = '<div class="myclass">';
        $html.= '<a href="http://example.com/image.gif">Lorem ipsum</a>';
        $html.= '</div>';

        $this->object->setText($html);
        $this->object->preserveHtmlTags(['a']);

        $this->assertNotEquals($html, $this->object->getText());

        $this->object->restore();
        $this->assertEquals($html, $this->object->getText());
    }

    /**
     * @covers Trefoil\Helpers\TextPreserver::preserveHtmlTagAttributes
     * @covers Trefoil\Helpers\TextPreserver::restore
     */
    public function testPreserveHtmlTagAttributes()
    {
        $html = '<div class="myclass">';
        $html.= '<a href="http://example.com/image.gif">Lorem ipsum</a>';
        $html.= '</div>';

        $this->object->setText($html);
        $this->object->preserveHtmlTagAttributes(['href', 'class']);

        $this->assertNotEquals($html, $this->object->getText());

        $this->object->restore();
        $this->assertEquals($html, $this->object->getText());
    }

    /**
     * @covers Trefoil\Helpers\TextPreserver::createPlacehoder
     * @todo   Implement testCreatePlacehoder().
     */
    public function testCreatePlacehoder()
    {
        $value = 'myvalue';
        $placeholder = $this->object->createPlacehoder($value, 'prefix');

        $html = '<div class="myclass">' . $value . '</div>';
        $html2 = str_replace('myvalue', $placeholder, $html);

        $this->object->setText($html2);
        $this->assertEquals($html2, $this->object->getText());

        $this->object->restore();
        $this->assertEquals($html, $this->object->getText());
    }

}
