<?php

namespace Trefoil\Helpers;

/**
 *
 */
class Activity
{

    /**
     * Activity type: Multiple questions, single answer ('A, B, C, D, E, ...')
     */
    const ACTIVITY_TYPE_ABC = 'abc';

    /**
     * Activity type: Multiple questions, Yes/No/Both answers
     */
    const ACTIVITY_TYPE_YNB = 'ynb';

    /**
     * Id of the activity (manually assigned)
     * @var string
     */
    protected $id;

    /**
     * Internal Id of the activity
     * @var string
     */
    protected $internalId;

    /**
     * Type of the activity
     * @var string
     * @see Activity::ACTIVITY_TYPE_ABC
     * @see Activity::ACTIVITY_TYPE_YNB
     */
    protected $type;

    /**
     * Options for this activity
     * @var Array of options
     */
    protected $options = array();

    /**
     * The heading for this activity
     * @var string
     */
    protected $heading;

    /**
     * The subheading for this activity
     * @var string
     */
    protected $subHeading;

    /**
     * The introduction text for this activity
     * @var string
     */
    protected $introduction;

    /**
     *
     * @var Array|ActivityQuestion
     */
    protected $questions = array();

    /* autogenerated getters and setters */

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    public function getInternalId()
    {
        return $this->internalId;
    }

    public function setInternalId($internalId)
    {
        $this->internalId = $internalId;
        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    public function getOptions()
    {
        return $this->options;
    }

    public function setOptions($options)
    {
        $this->options = $options;
        return $this;
    }

    public function getHeading()
    {
        return $this->heading;
    }

    public function setHeading($heading)
    {
        $this->heading = $heading;
        return $this;
    }

    public function getSubHeading()
    {
        return $this->subHeading;
    }

    public function setSubHeading($subHeading)
    {
        $this->subHeading = $subHeading;
        return $this;
    }

    public function getIntroduction()
    {
        return $this->introduction;
    }

    public function setIntroduction($introduction)
    {
        $this->introduction = $introduction;
        return $this;
    }

    public function getQuestions()
    {
        return $this->questions;
    }

    public function setQuestions(Array $questions)
    {
        $this->questions = $questions;
        return $this;
    }
}
