<?php

namespace Trefoil\Helpers;

/**
 */
class ActivityQuestion
{

    /**
     * Text of the question
     * @var string
     */
    protected $text;

    /**
     * Text of each response
     * @var Array|string
     */
    protected $responses    = array();

    /**
     *
     * @var Array|string
     * Optional explanation for each response
     */
    protected $explanations = array();

    /**
     * Index of the correct response
     * @var int
     */
    protected $solution;

    /* autogenerated getters and setters */

    public function getText()
    {
        return $this->text;
    }

    public function setText($text)
    {
        $this->text = $text;
        return $this;
    }

    public function getResponses()
    {
        return $this->responses;
    }

    public function setResponses(Array $responses)
    {
        $this->responses = $responses;
        return $this;
    }

    public function getExplanations()
    {
        return $this->explanations;
    }

    public function setExplanations(Array $explanations)
    {
        $this->explanations = $explanations;
        return $this;
    }

    public function getSolution()
    {
        return $this->solution;
    }

    public function setSolution($solution)
    {
        $this->solution = $solution;
        return $this;
    }
}
