<?php
declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

/**
 * A quiz item of type Questionnaire
 */
class QuizQuestionnaire extends QuizItem
{
    public const QUIZ_QUESTIONNAIRE = 'questionnaire';

    /**
     *
     * @var QuizQuestionnaireQuestion[]
     */
    protected $questions = [];

    public function __construct()
    {
        $this->setType(self::QUIZ_QUESTIONNAIRE);
    }

    /* autogenerated getters and setters */

    /**
     * @param QuizQuestionnaireQuestion[] $questions
     */
    public function setQuestions($questions): void
    {
        $this->questions = $questions;
    }

    /**
     * @return QuizQuestionnaireQuestion[]
     */
    public function getQuestions(): array
    {
        return $this->questions;
    }
}
