<?php
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

/**
 * An question in a quiz activity.
 */
class QuizActivityQuestion
{

    /**
     * Text of the question
     *
     * @var string
     */
    protected $text;

    /**
     * Text of each response
     *
     * @var Array|string
     */
    protected $responses = array();

    /**
     * Optional explanation for each response
     *
     * @var Array|string
     */
    protected $explanations = array();

    /**
     * Index of the correct response
     *
     * @var int
     */
    protected $solution;

    /* autogenerated getters and setters */

    /**
     * @param Array|string $explanations
     */
    public function setExplanations($explanations)
    {
        $this->explanations = $explanations;
    }

    /**
     * @return Array|string
     */
    public function getExplanations()
    {
        return $this->explanations;
    }

    /**
     * @param Array|string $responses
     */
    public function setResponses($responses)
    {
        $this->responses = $responses;
    }

    /**
     * @return Array|string
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * @param int $solution
     */
    public function setSolution($solution)
    {
        $this->solution = $solution;
    }

    /**
     * @return int
     */
    public function getSolution()
    {
        return $this->solution;
    }

    /**
     * @param string $text
     */
    public function setText($text)
    {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }
}
