<?php
declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

/**
 * A quiz item of type Activity.
 */
class QuizActivity extends QuizItem
{

    /** Activity type: Multiple questions, single answer ('A, B, C, D, E, ...') */
    public const QUIZ_ACTIVITY_TYPE_ABC = 'activity.abc';

    /** Activity type: Multiple questions, Yes/No/Both answers */
    public const QUIZ_ACTIVITY_TYPE_YNB = 'activity.ynb';

    /**
     * @var QuizActivityQuestion[]
     */
    protected $questions = [];

    /* autogenerated getters and setters */

    /**
     * @param QuizActivityQuestion[] $questions
     */
    public function setQuestions($questions): void
    {
        $this->questions = $questions;
    }

    /**
     * @return QuizActivityQuestion[]
     */
    public function getQuestions(): array
    {
        return $this->questions;
    }

}
