<?php

namespace Trefoil\Helpers;

/**
 * A quiz item of type Activity.
 */
class QuizActivity extends QuizItem
{

    /** Activity type: Multiple questions, single answer ('A, B, C, D, E, ...') */
    const QUIZ_ACTIVITY_TYPE_ABC = 'activity.abc';

    /** Activity type: Multiple questions, Yes/No/Both answers */
    const QUIZ_ACTIVITY_TYPE_YNB = 'activity.ynb';

    /**
     * @var Array|QuizActivityQuestion
     */
    protected $questions = array();

    /* autogenerated getters and setters */

    /**
     * @param Array|QuizActivityQuestion $questions
     */
    public function setQuestions($questions)
    {
        $this->questions = $questions;
    }

    /**
     * @return Array|QuizActivityQuestion
     */
    public function getQuestions()
    {
        return $this->questions;
    }

}
