<?php
declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

/**
 * An question in a quiz activity.
 */
class QuizActivityQuestion
{

    /**
     * Text of the question
     *
     * @var string
     */
    protected $text;

    /**
     * Text of each response
     *
     * @var string[]
     */
    protected $responses = [];

    /**
     * Optional explanation for each response
     *
     * @var string[]
     */
    protected $explanations = [];

    /**
     * Index of the correct response
     *
     * @var int
     */
    protected $solution;

    /* autogenerated getters and setters */

    /**
     * @param string[] $explanations
     */
    public function setExplanations($explanations): void
    {
        $this->explanations = $explanations;
    }

    /**
     * @return string[]
     */
    public function getExplanations(): array
    {
        return $this->explanations;
    }

    /**
     * @param string[] $responses
     */
    public function setResponses($responses): void
    {
        $this->responses = $responses;
    }

    /**
     * @return string[]
     */
    public function getResponses(): array
    {
        return $this->responses;
    }

    /**
     * @param int $solution
     */
    public function setSolution($solution): void
    {
        $this->solution = $solution;
    }

    /**
     * @return int
     */
    public function getSolution(): int
    {
        return $this->solution;
    }

    /**
     * @param string $text
     */
    public function setText($text): void
    {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getText(): string
    {
        return $this->text;
    }
}
