<?php
declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

/**
 * A question of a questionnaire
 */
class QuizQuestionnaireQuestion
{

    /**
     * Text of the question
     *
     * @var string
     */
    protected $text;

    /**
     * Heading of the solution
     *
     * @var string
     */
    protected $heading;

    /**
     * Text of the solution
     *
     * @var string
     */
    protected $solution;

    /* autogenerated getters and setters */

    /**
     * @param string $heading
     */
    public function setHeading($heading): void
    {
        $this->heading = $heading;
    }

    /**
     * @return string
     */
    public function getHeading(): ?string
    {
        return $this->heading;
    }

    /**
     * @param string $solution
     */
    public function setSolution($solution): void
    {
        $this->solution = $solution;
    }

    /**
     * @return string
     */
    public function getSolution(): ?string
    {
        return $this->solution;
    }

    /**
     * @param string $text
     */
    public function setText($text): void
    {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getText(): ?string
    {
        return $this->text;
    }

}
