<?php

namespace Trefoil\Helpers;

/**
 * A question of a questionnaire
 */
class QuizQuestionnaireQuestion
{

    /**
     * Text of the question
     *
     * @var string
     */
    protected $text;

    /**
     * Heading of the solution
     *
     * @var string
     */
    protected $heading;

    /**
     * Text of the solution
     *
     * @var string
     */
    protected $solution;

    /* autogenerated getters and setters */

    /**
     * @param string $heading
     */
    public function setHeading($heading)
    {
        $this->heading = $heading;
    }

    /**
     * @return string
     */
    public function getHeading()
    {
        return $this->heading;
    }

    /**
     * @param string $solution
     */
    public function setSolution($solution)
    {
        $this->solution = $solution;
    }

    /**
     * @return string
     */
    public function getSolution()
    {
        return $this->solution;
    }

    /**
     * @param string $text
     */
    public function setText($text)
    {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

}
