<?php
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Helpers;

/**
 * A quiz item of type Questionnaire
 */
class QuizQuestionnaire extends QuizItem
{
    const QUIZ_QUESTIONNAIRE = 'questionnaire';

    /**
     *
     * @var Array|QuizQuestionnaireQuestion
     */
    protected $questions = array();

    public function __construct()
    {
        $this->setType(self::QUIZ_QUESTIONNAIRE);
    }

    /* autogenerated getters and setters */

    /**
     * @param Array|QuizQuestionnaireQuestion $questions
     */
    public function setQuestions($questions)
    {
        $this->questions = $questions;
    }

    /**
     * @return Array|QuizQuestionnaireQuestion
     */
    public function getQuestions()
    {
        return $this->questions;
    }
}
