language: php

php:
  - 5.3
  - 5.4
  - 5.5

script: phpunit --coverage-clover=coverage.clover

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover