<?php

declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Tests\Command;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Tester\CommandTester;
use Trefoil\Console\Command\TrefoilVersionCommand;
use Trefoil\Console\ConsoleApplication;
use Trefoil\DependencyInjection\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 13:56:00.
 */
class TrefoilVersionCommandTest extends TestCase
{

    /**
     * @var ConsoleApplication
     */
    protected $console;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {

        // create the console application and add the tested command
        $app = new Application();
        $this->console = new ConsoleApplication($app);
        $this->console->add(new TrefoilVersionCommand());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public function testDisplayVersion(): void
    {
        /** @var TrefoilVersionCommand */
        $command = $this->console->find('version');

        $tester = new CommandTester($command);
        $tester->execute(
            [
                'command' => $command->getName()
            ]
        );

        /**
         * @var $app Application
         */
        $app = $command->getApp();

        static::assertStringContainsString('easybook installed version: ' . $app->getVersion(), $tester->getDisplay());
        static::assertStringContainsString('trefoil  installed version: ' . $app->getMyVersion(), $tester->getDisplay());
    }
}
