<?php

namespace Trefoil\Console\Command;

use Symfony\Component\Console\Tester\CommandTester;
use Trefoil\Console\ConsoleApplication;
use Trefoil\DependencyInjection\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 13:56:00.
 */
class TrefoilVersionCommandTest extends \PHPUnit_Framework_TestCase
{

    protected $console;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        // create the console application and add the tested command
        $app = new Application();
        $this->console = new ConsoleApplication($app);
        $this->console->add(new TrefoilVersionCommand());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testDisplayVersion()
    {
        $command = $this->console->find('version');

        $tester = new CommandTester($command);
        $tester->execute(
               array(
                   'command' => $command->getName()
               )
        );

        $app = $command->getApp();

        $this->assertContains('easybook installed version: ' . $app->getVersion(), $tester->getDisplay());
        $this->assertContains('trefoil  installed version: ' . $app->getMyVersion(), $tester->getDisplay());
    }

}
