book:
    title:            'easybook-books test Typography'
    author:           'Mags'
    edition:          '0'
    language:         es
    publication_date: '01-02-2013'

    generator:        { name: easybook, version: 5.0 DEV }
   
    contents:
        - { element: cover }
        - { element: toc   }
        - { element: edition  }
        - { element: chapter, number: 1, content: chapter1.md }

    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            use_html_toc:   true
            labels:         ['appendix', 'chapter', 'figure']  # labels also available for: "figure", "table"
            theme:          theme1
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part", "introduction", "usage-instructions"]
                
            isbn:           123456789X
            
            plugins:        
                - Typography
                            
        fold:
            format:         epub
            highlight_code: false
            include_styles: true
            use_html_toc:   true
            labels:         ['appendix', 'chapter', 'figure']  # labels also available for: "figure", "table"
            theme:          fold
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part", "introduction", "usage-instructions"]
                
            isbn:           123456789X
            
            plugins:        
                - Typography
                            