easybook:
    parameters:
        parser.options:
            code_block_type: fenced
        kindlegen.path: '/usr/local/bin/kindlegen'
        epubcheck.path: '/usr/local/bin/epubcheck.jar'
book:
    title:            'Trefoil documentation'
    author:           'Miguel A. Gabriel - magabriel@gmail.com'
    edition:          '2019'
    language:         en
    publication_date: ~

    version:          '1.959'

    generator:        { name: trefoil, version: DEV }

    contents:
        - { element: cover,        editions: [print] }
        - { element: edition }
        - { element: toc }
        - { element: introduction, content: introduction.md }

        - { element: part,        number: 1,    content: part-1.md }
        - { element: chapter,     number:   1,  content: chapter1.md }

        - { element: part,        number: 2,    content: part-2.md }
        - { element: chapter,     number:   2,  content: chapter2.md }
        - { element: chapter,     number:   3,  content: chapter3.md }
        - { element: chapter,     number:   4,  content: chapter4.md }
        - { element: chapter,     number:   5,  content: chapter5.md }
        - { element: chapter,     number:   6,  content: chapter6.md }

        - { element: part,        number: 3,    content: part-3.md }
        - { element: chapter,     number:   7,  content: chapter7.md }

        - { element: part,        number: 4,    content: part-4.md }
        - { element: chapter,     number:   8,  content: chapter8.md }
        
        - { element: footnotes }
        - { element: auto-index }
        - { element: lot }
        - { element: lof }
        - { element: auto-glossary, editions:[ebook, kindle, print] }
        - { element: ebook-quiz-solutions }

    editions:
        base-edition:
            highlight_code: true
            highlight_cache: true
            include_styles: true

            include_fonts:  true
            fonts:
                - Inconsolata-Regular
                - Inconsolata-Bold

            labels:         ['appendix', 'chapter', 'figure', 'part', 'illustration']
            theme:          TrefoilDoc
            toc:
                deep:        3
                elements:
                    - appendix
                    - chapter
                    - part
                    - introduction
                    - auto-index
                    - auto-glossary
                    - toc
                    - lof
                    - lot
            plugins:
                enabled:
                    - AutoGlossary
                    - AutoIndex
                    - DropCaps
                    - EbookRename
                    #- EpubCheck                # Uncomment to run the check
                    - QualityControl
                    - EpubUncompress
                    - FootnotesExtend
                    - HtmlTweaks
                    - ImageExtra
                    #- KindleTweaks             # disabled because interferes with EbookQuiz
                    - LinkCheck
                    - TableExtra
                    - TwigExtension
                    - Typography
                    - VersionUpdater
                    - EbookQuiz
                    - Illustrations
                    - LiteralLists
                    - TabularLists
                    - WordSearch
                    - WordFillIn
                    - Paperdle

                options:
                    DropCaps:
                        levels:     [1]                             # 1 to 6 (default: 1)
                        mode:       letter                          # letter, word (default: letter)
                        length:     1                               # number of letters or words to highlight (default: 1)
                        elements:   ['chapter', 'introduction']     # which elements to process

                    TwigExtension:
                        itemtoc:
                            deep:   2

                    LinkCheck:
                        check_external_links: false

                    EbookRename:
                        schema:         '{publishing.book.slug}-{book.version}' # syntax like twig but with single curlies
                        keep_original:  true

                    Typography:
                        checkboxes: true
                        fix_spanish_style_dialog: false

                    FootnotesExtend:
                        type: item  # (end, inject, item, inline)

                    WordSearch:
                        grid_size: 20
                        solution_grid_size: 20
                        highlight_type: line
                        word_files:
                            - { label: word_file_1, name: word_file_1.txt }

                    WordFillIn:
                        grid_size: 20
                        solution_grid_size: 20
                        highlight_type: line
                        word_files:
                            - { label: word_file_1, name: word_file_1.txt }

                    Paperdle:
                        alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                        tries: 6
                        markers: "O/#"
                        strings:
                            board:
                                title: "Puzzle %s"
                                text: "Guess the word in the grid"
                                text2: >
                                    Use Table 1 and Table 2 to evaluate each letter in your guess.<br>
                                    Draw a circle over the correct letters, and a line over the misplaced letters.
                            letters:
                                title: "Letters"
                                text: "Cross out the used letters"
                            randomizer:
                                title: "Table 1"
                                text: "Look up each letter in your guess to get the key for Table 2"
                            decoder:
                                title: "Table 2"
                                text: "Look up the key you got from Table 1 to get the letter's evaluation"
                                text2: >
                                    O ➔ Letter is correct<br>
                                    / ➔ Letter is misplaced<br>
                                    # ➔ Wrong letter
                            solution:
                                title: "Solution"
                                text: "The solution is encoded. Use Table 3 to decode it."
                            solution-decoder:
                                title: "Table 3"
                                text: "Look up each component of the encoded solution to decode it"

        ebook:
            extends:         base-edition
            format:          epub

        kindle:
            extends:         base-edition
            format:          mobi
              
        doc-website:
            extends:         base-edition
            format:          html
            include_styles:  true
            highlight_code:  true
            toc:
              deep:        3
              elements:
                - appendix
                - chapter
                - part
                - introduction
                - auto-index
                - lof
                - lot

        doc-website-local: # Like doc-website for local test
            extends:         base-edition # Cannot extend from an already-extended edition
            format:          html
            include_styles:  true
            highlight_code:  true
            is_local:        true # Forces usage of explicit https to load net resources
            toc:
                deep:        3
                elements:
                    - appendix
                    - chapter
                    - part
                    - introduction
                    - auto-index
                    - lof
                    - lot

        print:
            debug: true
            extends:         base-edition
            format:          pdf
            has_cover_image: true
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            two_sided:      false
            plugins:
                options:
                    FootnotesExtend:
                        type: inline
