book:
    title:            "FOL digital: Volumen de muestra para promoción"
    
    author: ~
    authors:           
      - "Francisco Javier Carrascal Andrade"
      - "Teresa Ginés González"
      - "María de las Nieves Mendoza Roldán"
      - "Esther Puchades Muñoz"
      
    #reviewer:          
    #  - "Teresa Ginés"
      
    edition:          "0"
    language:         es
    publication_date: ~

    series:          "Formación y Orientación Laboral"
    description:      > 
       Volumen X de Formación y Orientación Laboral

    version:          "1.43"
    #version_options:
    #  increment_ver:  false
    #  increment_rev:  true
      
    subject:          
      - "Libro de texto"
      - "Formación Profesional"
      - "FP"
      - "Formación y Orientación Laboral"
      - "FOL"

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: edition }
        - { element: toc }
        - { element: usage-instructions }
        
        - { element: introduction, number:  0,    content: introduccion.md }

        # PART A
        - { element: part,         number:  A,    content: part-a.md }
        - { element: chapter,      number:    1,  content: chapter-salud-laboral.md }
        - { element: chapter,      number:    2,  content: chapter-equipos.md }

        - { element: part,         number:  B,    content: part-b.md }
        - { element: chapter,      number:    3,  content: chapter-busqueda-de-empleo.md }
        - { element: chapter,      number:    4,  content: chapter-conflictos.md }
        
        - { element: end-of-contents }
        - { element: solutions, number: 1 }
        - { element: auto-glossary, number: 1 }

    editions:
        fold-revisable:
            format:          html
            include_styles:  true
            highlight_cache: false
            highlight_code:  false
            labels:          ['part', 'appendix', 'chapter', 'figure']
            theme:           fold
            toc:
                deep:        2
                elements:   ["appendix", "chapter", "part", "introduction", "usage-instructions"]
                         
            plugins:        
                - LinkCheck
                - AutoGlossary
                - Typography
                #- ConfigOptionsInContent
                - ThemeImages
                - TwigExtension 
                - TableExtra
                

        fold:
            format:         epub
            highlight_code: false
            include_styles: true
            use_html_toc:   true
            labels:         ['part', 'appendix', 'chapter', 'figure']  # "figure", "table"
            theme:          fold
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part", "introduction", "usage-instructions"]
                
            #isbn:           123456789X
            epub_rename:    '{publishing.book.slug}-V{book.edition}.{book.version}'
            itemtoc:
                 deep:       3
                 
            #check_external_links: false
            plugins:        
                - LinkCheck
                - EpubActivities
                - EpubQuestions
                - AutoGlossary
                - Typography
                - ThemeImages
                - EpubBookRename
                - EpubUncompress
                - VersionUpdater
                #- KindleTweaks NO FUNCIONA
                - TwigExtension 
                - TableExtra
                - EpubQualityControl
                            
