<?php
declare(strict_types=1);
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Trefoil\Plugins\Optional;

use Easybook\Events\BaseEvent;
use Easybook\Events\EasybookEvents;
use Easybook\Events\ParseEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Trefoil\Plugins\BasePlugin;

/**
 * This plugin fixes footnotes.
 *
 * @deprecated
 * It replaces invalid character ':' in footnotes ids generated by the
 * Markdown parser (so epubcheck will not complain).
 */
class FootnotesFixPlugin extends BasePlugin implements EventSubscriberInterface
{
    /* ********************************************************************************
     * Event handlers
     * ********************************************************************************
     */
    /**
     * @return array
     */
    public static function getSubscribedEvents(): array
    {
        return [
            EasybookEvents::POST_PARSE   => ['onItemPostParse'],
            EasybookEvents::POST_PUBLISH => 'onPostPublish',
        ];
    }

    /**
     * @param ParseEvent $event
     */
    public function onItemPostParse(ParseEvent $event)
    {
        $this->init($event);

        $this->processItem();

        // reload changed item
        $event->setItem($this->item);
    }

    /**
     * @param BaseEvent $event
     */
    public function onPostPublish(BaseEvent $event)
    {
        $this->init($event);

        $this->deprecationNotice();
    }

    /* ********************************************************************************
     * Implementation
     * ********************************************************************************
     */

    /**
     * For a content item to be processed, extract generated footnotes.
     */
    protected function processItem()
    {
        $this->fixFootnotes();
    }

    protected function fixFootnotes()
    {
        $content = $this->item['content'];

        // fix footnotes ref in text
        $content = preg_replace('/id="fnref(\d*):/', 'id="fnref$1-', $content);
        $content = str_replace('href="#fn:', 'href="#fn-', $content);

        // fix footnotes
        $content = str_replace('id="fn:', 'id="fn-', $content);
        $content = preg_replace('/href="#fnref(\d*):/', 'href="#fnref$1-', $content);

        // fix return sign used
        $content = str_replace('&#8617;', '[&crarr;]', $content);

        $this->item['content'] = $content;
    }
}
