<?php
/*
 * This file is part of the trefoil application.
 *
 * (c) Miguel Angel Gabriel <magabriel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Trefoil\Plugins\Optional;

use Easybook\Events\BaseEvent;
use Easybook\Events\EasybookEvents;
use Easybook\Events\ParseEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Trefoil\Plugins\BasePlugin;
use Trefoil\Util\SimpleReport;

/**
 * This plugin fixes footnotes.
 *
 * It replaces invalid character ':' in footnotes ids generated by the
 * Markdown parser (so epubcheck will not complain).
 *
 */
class FootnotesFixPlugin extends BasePlugin implements EventSubscriberInterface
{
    /* ********************************************************************************
     * Event handlers
     * ********************************************************************************
     */
    public static function getSubscribedEvents()
    {
        return array(
            EasybookEvents::POST_PARSE   => array('onItemPostParse')
        );
    }

    public function onItemPostParse(ParseEvent $event)
    {
        $this->init($event);

        if (!in_array($this->format, array('Epub', 'Mobi', 'Html'))) {
            // not for this format
            return;
        }

        $this->processItem();

        // reload changed item
        $event->setItem($this->item);
    }

    /* ********************************************************************************
     * Implementation
     * ********************************************************************************
     */

    /**
     * For a content item to be processed, extract generated footnotes.
     */
    protected function processItem()
    {
        $this->fixFootnotes();
    }

    protected function fixFootnotes()
    {
        $content = $this->item['content'];

        // fix footnotes ref in text
        $content = str_replace('id="fnref:', 'id="fnref-', $content);
        $content = str_replace('href="#fn:', 'href="#fn-', $content);

        // fix footnotes
        $content = str_replace('id="fn:', 'id="fn-', $content);
        $content = str_replace('href="#fnref:', 'href="#fnref-', $content);

        // fix return sign used
        $content = str_replace('&#8617;', '[&crarr;]', $content);
        
        $this->item['content'] = $content;
    }
}
